
version: '2'

services:

  mfan:
    build: ./images
    image: mfan:3.5
    container_name: mfan
    volumes:
      - ./:/app
      
    working_dir: /app
#    ports: 
#      - 88:27004
    command: "/run/start.sh"
    # command: "ls -all /run"
    # restart: always

  ngx:
    image: nginx:1.14.0-alpine
    container_name: mfan_ngx
    ports:
      - 27004:27004
    volumes:
      - ./images/:/etc/nginx/conf.d
      - ./:/usr/share/nginx/html
    depends_on:
      - mfan
    # restart: always