
version: '2'

services:
  # msq:
  #   image: mysql:5.7
  #   volumes:
  #     - ./mysql/conf.d:/etc/mysql/conf.d
  #     - ~/fanhaodb:/var/lib/mysql
  #   # ports: 
  #   #   - 3306:3306
  #   command: --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci
  #   environment:
  #     - MYSQL_ROOT_PASSWORD=helloworld
  #     - MYSQL_DATABASE=fanhao
  #   restart: always

  mfan:
    build: ./conf.d
    image: mfan:3.5
    volumes:
      - ./:/app
    # ports: 
    #   - 81:81
    command: python3 /app/app.py
    # depends_on:
    #   - msq
    restart: always

  ngx:
    image: nginx:1.14.0-alpine
    ports:
      - 81:81
    volumes:
      - ./conf.d/:/etc/nginx/conf.d
      - ./:/usr/share/nginx/html
    depends_on:
      - mfan
    restart: always