
version: '2'

services:

  mfans:
    build: ./images
    image: mfans:3.5
    container_name: mfans
    volumes:
      - ./:/app
      - ./conf.d/polipo.conf:/etc/polipo/config
      
    working_dir: /app
    ports: 
      - 88:27004
    command: "/run/start.sh"
    restart: always

  ngx:
    image: nginx:1.14.0-alpine
    container_name: mfans_ngx
    ports:
      - 27004:27004
    volumes:
      - ./images/:/etc/nginx/conf.d
      - ./:/usr/share/nginx/html
    depends_on:
      - mfans
    restart: always